const iconNames = [
  'heartFull',
  'heart',
  'spinner',
  'settings',
  'list',
  'comment',
  'bookmark',
  'bookmarkFull',
  'close',
  'chevronDown',
  'arrowRightLeft',
  'arrowLongDown',
  'check',
  'user',
  'moon',
  'sun',
  'arrowRightOnRectangle',
  'listBullet',
  'search',
  'bars3',
  'logo',
  'trash',
  'google',
  'vk',
  'lock',
  'wrenchScrewdriver',
] as const

export type IconType = (typeof iconNames)[number]
